import { useState } from "react";
import api from "../services/api";

export default function AIAnalysis() {
  const [message, setMessage] = useState(
    "I cannot connect to VPN since this morning. Authentication keeps failing."
  );
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);

  const analyzeRequest = async () => {
    if (!message.trim()) return;

    setLoading(true);
    setResult(null);

    try {
      const response = await api.post("/tickets/intake", {
        message,
      });

      setResult(response.data);
    } catch (error) {
      console.error(error);

      setResult({
        error: true,
        message: "Unable to connect to the AI analysis service.",
      });
    } finally {
      setLoading(false);
    }
  };

  const loadExample = (text) => {
    setMessage(text);
    setResult(null);
  };

  const analysis = result?.analysis;

  return (
    <div>
      <div className="page-header">
        <h1>AI Analysis</h1>
        <p>
          View how the AI interprets an employee request and routes it through
          the ITSM workflow.
        </p>
      </div>

      {/* Request Input */}
      <div className="panel">
        <div className="panel-header">
          <div>
            <h2>Analyze Employee Request</h2>
            <p className="panel-description">
              The request is classified and enriched with enterprise knowledge
              before the appropriate workflow is triggered.
            </p>
          </div>

          <span className="kb-status">AI Router Active</span>
        </div>

        <textarea
          className="analysis-input"
          rows="4"
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          placeholder="Enter an employee IT request..."
        />

        <div className="analysis-actions">
          <button
            className="primary-button"
            onClick={analyzeRequest}
            disabled={loading}
          >
            {loading ? "Analyzing..." : "Analyze Request"}
          </button>

          <button
            className="example-button"
            onClick={() =>
              loadExample(
                "My password has expired and I cannot log in."
              )
            }
          >
            Password Issue
          </button>

          <button
            className="example-button"
            onClick={() =>
              loadExample("I need Visual Studio Code installed.")
            }
          >
            Software Request
          </button>

          <button
            className="example-button"
            onClick={() =>
              loadExample("My Outlook emails are not syncing.")
            }
          >
            Outlook Issue
          </button>
        </div>
      </div>

      {/* Error */}
      {result?.error && (
        <div className="panel error-panel">
          <strong>Analysis Error</strong>
          <p>{result.message}</p>
        </div>
      )}

      {/* Analysis Result */}
      {result && !result.error && analysis && (
        <>
          <div className="analysis-overview">
            <div className="analysis-highlight">
              <span>Intent</span>
              <strong>{analysis.intent}</strong>
            </div>

            <div className="analysis-highlight">
              <span>Confidence</span>
              <strong>
                {(analysis.confidence * 100).toFixed(0)}%
              </strong>
            </div>

            <div className="analysis-highlight">
              <span>Priority</span>
              <strong>{analysis.priority}</strong>
            </div>

            <div className="analysis-highlight">
              <span>Automation</span>
              <strong>
                {analysis.automation_candidate ? "Candidate" : "No"}
              </strong>
            </div>
          </div>

          {/* Classification */}
          <div className="panel">
            <div className="panel-header">
              <div>
                <h2>AI Classification</h2>
                <p className="panel-description">
                  Structured information generated by the request router.
                </p>
              </div>
            </div>

            <div className="analysis-details-grid">
              <div className="analysis-detail">
                <label>Intent</label>
                <strong>{analysis.intent}</strong>
              </div>

              <div className="analysis-detail">
                <label>Category</label>
                <strong>{analysis.category}</strong>
              </div>

              <div className="analysis-detail">
                <label>Subcategory</label>
                <strong>{analysis.subcategory}</strong>
              </div>

              <div className="analysis-detail">
                <label>Priority</label>
                <strong>{analysis.priority}</strong>
              </div>

              <div className="analysis-detail">
                <label>Impact</label>
                <strong>{analysis.impact}</strong>
              </div>

              <div className="analysis-detail">
                <label>Urgency</label>
                <strong>{analysis.urgency}</strong>
              </div>

              <div className="analysis-detail">
                <label>Assignment Group</label>
                <strong>{analysis.assignment_group}</strong>
              </div>

              <div className="analysis-detail">
                <label>Summary</label>
                <strong>{analysis.summary}</strong>
              </div>
            </div>
          </div>

          {/* Decision + Resolution */}
          <div className="analysis-two-column">
            <div className="panel">
              <h2>AI Decision</h2>

              <div className="decision-box">
                <div>
                  <label>Confidence</label>
                  <strong>
                    {(analysis.confidence * 100).toFixed(0)}%
                  </strong>
                </div>

                <div>
                  <label>Automation Candidate</label>
                  <strong>
                    {analysis.automation_candidate
                      ? "Yes"
                      : "No"}
                  </strong>
                </div>

                <div>
                  <label>Recommended Route</label>
                  <strong>
                    {analysis.intent === "Knowledge Question"
                      ? "Knowledge / RAG"
                      : analysis.intent === "Service Request"
                      ? "Service Request"
                      : analysis.intent === "Automatable Issue"
                      ? "Self-Healing"
                      : "Incident Management"}
                  </strong>
                </div>
              </div>
            </div>

            <div className="panel">
              <h2>Suggested Resolution</h2>

              <div className="resolution-box">
                {result.suggested_resolution ||
                  "No resolution available."}
              </div>
            </div>
          </div>

          {/* Knowledge */}
          <div className="panel">
            <div className="panel-header">
              <div>
                <h2>Knowledge Evidence</h2>
                <p className="panel-description">
                  Sources retrieved from the approved knowledge base.
                </p>
              </div>

              <span className="kb-status">
                {result.knowledge_sources?.length || 0} Sources
              </span>
            </div>

            {result.knowledge_sources?.length > 0 ? (
              <div className="analysis-sources">
                {result.knowledge_sources.map((source) => (
                  <div
                    className="analysis-source"
                    key={source.article_id}
                  >
                    <div>
                      <strong>
                        {source.article_id} — {source.title}
                      </strong>

                      <span>
                        {source.category}
                      </span>
                    </div>

                    <strong>
                      {(
                        source.similarity_score * 100
                      ).toFixed(1)}
                      %
                    </strong>
                  </div>
                ))}
              </div>
            ) : (
              <div className="empty-state">
                No approved knowledge source was retrieved.
              </div>
            )}
          </div>

          {/* ServiceNow */}
          <div className="panel">
            <div className="panel-header">
              <div>
                <h2>ServiceNow Integration</h2>
                <p className="panel-description">
                  ITSM record generated by the workflow.
                </p>
              </div>

              <span className="kb-status">
                {result.servicenow
                  ? "Record Created"
                  : "No Record"}
              </span>
            </div>

            {result.servicenow ? (
              <div className="servicenow-analysis">
                <div>
                  <label>Reference</label>
                  <strong>
                    {result.servicenow.number}
                  </strong>
                </div>

                <div>
                  <label>State</label>
                  <strong>
                    {result.servicenow.state}
                  </strong>
                </div>

                <div>
                  <label>Integration</label>
                  <strong>Mock ServiceNow API</strong>
                </div>
              </div>
            ) : (
              <div className="empty-state">
                This request does not require a ServiceNow incident.
              </div>
            )}
          </div>
        </>
      )}
    </div>
  );
}